// Code generated by MockGen. DO NOT EDIT.
// Source: miner.go

// Package miner is a generated GoMock package.
package miner

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNodeClient is a mock of NodeClient interface.
type MockNodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockNodeClientMockRecorder
}

// MockNodeClientMockRecorder is the mock recorder for MockNodeClient.
type MockNodeClientMockRecorder struct {
	mock *MockNodeClient
}

// NewMockNodeClient creates a new mock instance.
func NewMockNodeClient(ctrl *gomock.Controller) *MockNodeClient {
	mock := &MockNodeClient{ctrl: ctrl}
	mock.recorder = &MockNodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeClient) EXPECT() *MockNodeClientMockRecorder {
	return m.recorder
}

// SubmitBlock mocks base method.
func (m *MockNodeClient) SubmitBlock(prev, wallet string, nonce int, ts int64, hash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBlock", prev, wallet, nonce, ts, hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SubmitBlock indicates an expected call of SubmitBlock.
func (mr *MockNodeClientMockRecorder) SubmitBlock(prev, wallet, nonce, ts, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBlock", reflect.TypeOf((*MockNodeClient)(nil).SubmitBlock), prev, wallet, nonce, ts, hash)
}
