// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package stats is a generated GoMock package.
package stats

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNodeClient is a mock of NodeClient interface.
type MockNodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockNodeClientMockRecorder
}

// MockNodeClientMockRecorder is the mock recorder for MockNodeClient.
type MockNodeClientMockRecorder struct {
	mock *MockNodeClient
}

// NewMockNodeClient creates a new mock instance.
func NewMockNodeClient(ctrl *gomock.Controller) *MockNodeClient {
	mock := &MockNodeClient{ctrl: ctrl}
	mock.recorder = &MockNodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeClient) EXPECT() *MockNodeClientMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockNodeClient) GetBalance(addr string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", addr)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockNodeClientMockRecorder) GetBalance(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockNodeClient)(nil).GetBalance), addr)
}

// MockWallets is a mock of Wallets interface.
type MockWallets struct {
	ctrl     *gomock.Controller
	recorder *MockWalletsMockRecorder
}

// MockWalletsMockRecorder is the mock recorder for MockWallets.
type MockWalletsMockRecorder struct {
	mock *MockWallets
}

// NewMockWallets creates a new mock instance.
func NewMockWallets(ctrl *gomock.Controller) *MockWallets {
	mock := &MockWallets{ctrl: ctrl}
	mock.recorder = &MockWalletsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWallets) EXPECT() *MockWalletsMockRecorder {
	return m.recorder
}

// GetWallets mocks base method.
func (m *MockWallets) GetWallets() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallets")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetWallets indicates an expected call of GetWallets.
func (mr *MockWalletsMockRecorder) GetWallets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallets", reflect.TypeOf((*MockWallets)(nil).GetWallets))
}

// MockWebDashBoard is a mock of WebDashBoard interface.
type MockWebDashBoard struct {
	ctrl     *gomock.Controller
	recorder *MockWebDashBoardMockRecorder
}

// MockWebDashBoardMockRecorder is the mock recorder for MockWebDashBoard.
type MockWebDashBoardMockRecorder struct {
	mock *MockWebDashBoard
}

// NewMockWebDashBoard creates a new mock instance.
func NewMockWebDashBoard(ctrl *gomock.Controller) *MockWebDashBoard {
	mock := &MockWebDashBoard{ctrl: ctrl}
	mock.recorder = &MockWebDashBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebDashBoard) EXPECT() *MockWebDashBoardMockRecorder {
	return m.recorder
}

// BroadcastUpdate mocks base method.
func (m *MockWebDashBoard) BroadcastUpdate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastUpdate")
}

// BroadcastUpdate indicates an expected call of BroadcastUpdate.
func (mr *MockWebDashBoardMockRecorder) BroadcastUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastUpdate", reflect.TypeOf((*MockWebDashBoard)(nil).BroadcastUpdate))
}
