// Code generated by MockGen. DO NOT EDIT.
// Source: wallets.go

// Package wallets is a generated GoMock package.
package wallets

import (
	reflect "reflect"
	types "shminer/backend/types"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetSessionPassword mocks base method.
func (m *MockStorage) GetSessionPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSessionPassword indicates an expected call of GetSessionPassword.
func (mr *MockStorageMockRecorder) GetSessionPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionPassword", reflect.TypeOf((*MockStorage)(nil).GetSessionPassword))
}

// GetStorage mocks base method.
func (m *MockStorage) GetStorage() types.StorageData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorage")
	ret0, _ := ret[0].(types.StorageData)
	return ret0
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockStorageMockRecorder) GetStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorage", reflect.TypeOf((*MockStorage)(nil).GetStorage))
}

// SaveStorage mocks base method.
func (m *MockStorage) SaveStorage(password string, data types.StorageData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStorage", password, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStorage indicates an expected call of SaveStorage.
func (mr *MockStorageMockRecorder) SaveStorage(password, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStorage", reflect.TypeOf((*MockStorage)(nil).SaveStorage), password, data)
}

// UpdateWallets mocks base method.
func (m *MockStorage) UpdateWallets(newWallets []types.WalletStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateWallets", newWallets)
}

// UpdateWallets indicates an expected call of UpdateWallets.
func (mr *MockStorageMockRecorder) UpdateWallets(newWallets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWallets", reflect.TypeOf((*MockStorage)(nil).UpdateWallets), newWallets)
}
