// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddWallet(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ChangePassword(arg1:string,arg2:string):Promise<string>;

export function DeleteWallet(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<backend.AppConfig>;

export function GetDashboardData():Promise<backend.DashboardData>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetWalletJSONSecure(arg1:string,arg2:string):Promise<string>;

export function GetWalletKey(arg1:string,arg2:string):Promise<string>;

export function GetWallets():Promise<Array<string>>;

export function ImportWalletJSON(arg1:string):Promise<string>;

export function InitStorage(arg1:string):Promise<string>;

export function IsStorageInitialized():Promise<boolean>;

export function RenameWallet(arg1:string,arg2:string):Promise<string>;

export function SetGlobalMining(arg1:boolean):Promise<void>;

export function ToggleWallet(arg1:string):Promise<boolean>;

export function UnlockStorage(arg1:string):Promise<string>;

export function UpdateConfig(arg1:backend.AppConfig,arg2:string):Promise<string>;

export function UpdateWalletKey(arg1:string,arg2:string,arg3:string):Promise<string>;
