// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {types} from '../models';

export function AddWallet(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ChangePassword(arg1:string,arg2:string):Promise<string>;

export function CheckAndApplyUpdate():Promise<string>;

export function DeleteWallet(arg1:string,arg2:string):Promise<string>;

export function GenerateKeyPair():Promise<Record<string, string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetConfigFilePath():Promise<string>;

export function GetDashboardData():Promise<types.DashboardData>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetWalletJSONSecure(arg1:string,arg2:string):Promise<string>;

export function GetWalletKey(arg1:string,arg2:string):Promise<string>;

export function GetWallets():Promise<Array<string>>;

export function ImportWalletJSON(arg1:string):Promise<string>;

export function InitStorage(arg1:string):Promise<string>;

export function IsStorageInitialized():Promise<boolean>;

export function OpenConfigFolder():Promise<void>;

export function RenameWallet(arg1:string,arg2:string):Promise<string>;

export function SendMessageToDeveloper(arg1:string,arg2:string):Promise<void>;

export function SendTransaction(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function SetGlobalMining(arg1:boolean):Promise<void>;

export function ToggleWallet(arg1:string):Promise<boolean>;

export function TryAutoLogin():Promise<boolean>;

export function UnlockStorage(arg1:string):Promise<string>;

export function UpdateConfig(arg1:config.AppConfig,arg2:string):Promise<string>;

export function UpdateWalletKey(arg1:string,arg2:string,arg3:string):Promise<string>;
