// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWallet(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWallet'](arg1, arg2, arg3);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckAndApplyUpdate() {
  return window['go']['main']['App']['CheckAndApplyUpdate']();
}

export function DeleteWallet(arg1, arg2) {
  return window['go']['main']['App']['DeleteWallet'](arg1, arg2);
}

export function GenerateKeyPair() {
  return window['go']['main']['App']['GenerateKeyPair']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigFilePath() {
  return window['go']['main']['App']['GetConfigFilePath']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetWalletJSONSecure(arg1, arg2) {
  return window['go']['main']['App']['GetWalletJSONSecure'](arg1, arg2);
}

export function GetWalletKey(arg1, arg2) {
  return window['go']['main']['App']['GetWalletKey'](arg1, arg2);
}

export function GetWallets() {
  return window['go']['main']['App']['GetWallets']();
}

export function ImportWalletJSON(arg1) {
  return window['go']['main']['App']['ImportWalletJSON'](arg1);
}

export function InitStorage(arg1) {
  return window['go']['main']['App']['InitStorage'](arg1);
}

export function IsStorageInitialized() {
  return window['go']['main']['App']['IsStorageInitialized']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function RenameWallet(arg1, arg2) {
  return window['go']['main']['App']['RenameWallet'](arg1, arg2);
}

export function SendMessageToDeveloper(arg1, arg2) {
  return window['go']['main']['App']['SendMessageToDeveloper'](arg1, arg2);
}

export function SendTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3, arg4);
}

export function SetGlobalMining(arg1) {
  return window['go']['main']['App']['SetGlobalMining'](arg1);
}

export function ToggleWallet(arg1) {
  return window['go']['main']['App']['ToggleWallet'](arg1);
}

export function TryAutoLogin() {
  return window['go']['main']['App']['TryAutoLogin']();
}

export function UnlockStorage(arg1) {
  return window['go']['main']['App']['UnlockStorage'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}

export function UpdateWalletKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWalletKey'](arg1, arg2, arg3);
}
