// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWallet(arg1, arg2, arg3) {
  return ObfuscatedCall(0, [arg1, arg2, arg3]);
}

export function ChangePassword(arg1, arg2) {
  return ObfuscatedCall(1, [arg1, arg2]);
}

export function DeleteWallet(arg1, arg2) {
  return ObfuscatedCall(2, [arg1, arg2]);
}

export function GetConfig() {
  return ObfuscatedCall(3, []);
}

export function GetDashboardData() {
  return ObfuscatedCall(4, []);
}

export function GetWalletKey(arg1, arg2) {
  return ObfuscatedCall(5, [arg1, arg2]);
}

export function GetWallets() {
  return ObfuscatedCall(6, []);
}

export function InitStorage(arg1) {
  return ObfuscatedCall(7, [arg1]);
}

export function IsStorageInitialized() {
  return ObfuscatedCall(8, []);
}

export function RenameWallet(arg1, arg2) {
  return ObfuscatedCall(9, [arg1, arg2]);
}

export function SendTransaction(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(10, [arg1, arg2, arg3, arg4]);
}

export function SetGlobalMining(arg1) {
  return ObfuscatedCall(11, [arg1]);
}

export function ToggleWallet(arg1) {
  return ObfuscatedCall(12, [arg1]);
}

export function UnlockStorage(arg1) {
  return ObfuscatedCall(13, [arg1]);
}

export function UpdateConfig(arg1, arg2) {
  return ObfuscatedCall(14, [arg1, arg2]);
}

export function UpdateWalletKey(arg1, arg2, arg3) {
  return ObfuscatedCall(15, [arg1, arg2, arg3]);
}
